"""table init

Revision ID: 7662dd37faf2
Revises: 
Create Date: 2025-07-06 01:40:49.406869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7662dd37faf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('redirect_url', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='urlstatus'), nullable=True),
    sa.Column('last_interacted_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='url_shortener'
    )
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_table('urls', schema='url_shortener')
    # ### end Alembic commands ###
